### ISSUE TITLE
之前运行的好好的，昨天突然报错，而且无法启动了，求大佬看看是啥情况

### ISSUE THREAD

**Issue by smallmj** [Souloco/StarRail-FastRun#33]
运行 fastrun.exe是这样：

Active code page: 65001

本项目开源免费，仅供学习交流使用

本项目地址:https://github.com/Souloco/StarRail-FastRun

Waiting for 0 seconds, press a key to continue ...

Traceback (most recent call last):

  File "C:\Users\Alan\Downloads\StarRail-FastRun-V1.9.1\FastStart.py", line 1, in <module>

    from utils.config import get_config

  File "C:\Users\Alan\Downloads\StarRail-FastRun-V1.9.1\utils\config.py", line 3, in <module>

    import cv2 as cv

ModuleNotFoundError: No module named 'cv2'

Press any key to continue . . .

gui.exe打不开
运行steup.exe是这样：

Active code page: 65001
本项目开源免费，仅供学习交流使用
本项目地址:https://github.com/Souloco/StarRail-FastRun
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
ERROR: Polygon3-3.0.9-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.
Press any key to continue . . .

**Comment by Souloco** [comment]
重新下载解压呢？

**Comment by Souloco** [comment]
应该不是依赖问题

**Comment by smallmj** [comment]
重新下载了还是一样

**Comment by Souloco** [comment]
你的python版本是3.11.X吗？如果不是可以自行安装Polygon3与psutil两个依赖库试试

**Comment by smallmj** [comment]
我昨天更新到3.12了，但是刚才把3.12卸载了，重新装了3.11，还是不行，现在电脑在跑别的脚本，等下跑完我再安装一下那两个依赖试试

**Comment by smallmj** [comment]
不行，连着两个依赖库都安装不了：

C:\Windows\System32>pip install polygon3
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting polygon3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1f/26/eea4112be43c8b7345477ad9150d499303494f32fb5951cb0f6e9104045b/Polygon3-3.0.9.1.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: polygon3
  Building wheel for polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      C:\Users\Alan\AppData\Local\Temp\pip-install-0fc9527a\polygon3_244e5391e8dd46eb876f2b065879f822\setup.py:39: SyntaxWarning: invalid escape sequence '\|'
        longdesc = """THIS VERSION WORKS WITH PYTHON-3.x ONLY!
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\Polygon
      copying Polygon\IO.py -> build\lib.win-amd64-cpython-312\Polygon
      copying Polygon\Shapes.py -> build\lib.win-amd64-cpython-312\Polygon
      copying Polygon\Utils.py -> build\lib.win-amd64-cpython-312\Polygon
      copying Polygon\__init__.py -> build\lib.win-amd64-cpython-312\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for polygon3
  Running setup.py clean for polygon3
Failed to build polygon3
ERROR: Could not build wheels for polygon3, which is required to install pyproject.toml-based projects

C:\Windows\System32>pip install psuti
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement psuti (from versions: none)
ERROR: No matching distribution found for psuti

**Comment by Souloco** [comment]
我只提供了本地依赖包的3.11版本,如果是3.12你就要自行安装，我提到的两个包你可能需要本地包来进行安装才能成功

**Comment by smallmj** [comment]
我现在是安装的你链接里面的3.11环境
